### ISSUE TITLE
Hello! I used this project as part of my dissertation.

### ISSUE THREAD

**Issue by Lan2u** [lschmierer/sacn#16]
Hi,

Wasn't sure where to put/discuss this.

As my final year dissertation project for my computer science degree I forked this project and then continued to develop it further implementing missing features such as universe synchronisation/discovery as well as support for Windows, Linux, IPv4 and IPv6. 

Now my degree is finished I'd like to distribute the code back into the open-source community, I have uploaded it to https://github.com/Lan2u/RustSacn and would love if you could check it out. It is significantly different (multiple API breaking changes were required) so I didn't think a fork/PR would be appropriate in this case but I could try and merge it into this repo depending on what people think.

In addition to the extra features, the library was also tested fairly extensively for compliance with the protocol (through unit tests, integration tests on a single machine, tests across multiple machines as-well-as tests with actual industry hardware/software).

Thoughts?

**Comment by lschmierer** [comment]
Hey,

really great work!
As no development happened on this repo, I do not see any reason in trying to merge your repo into this.

This library is currently published on https://crates.io/crates/sacn.
I currently don't have the capacity to actively maintain this project. If you want to take care of that, I would be happy to give you ownership to the crates.io package.

Something I have already thought about some time ago is to create a Github organisation for Lighting related projects. Maybe call it `rust-light`. Then we could put the SACN project there.

**Comment by Lan2u** [comment]
I would definitely be keen to take ownership of the crates.io package if you aren't able to maintain it anymore.

A github org sounds like a great idea :)

**Comment by lschmierer** [comment]
Sorry for coming back to you so late...
Unfortunately the invitation to the Org has expired 🙈
Can you invite me again?

Are you singen up on crates.io? Tried adding you as an owner but your Github username was not found.

**Comment by Lan2u** [comment]
> Sorry for coming back to you so late...
> Unfortunately the invitation to the Org has expired 🙈
> Can you invite me again?
> 
> Are you singen up on crates.io? Tried adding you as an owner but your Github username was not found.

Resent and I am now if you try again :)

**Comment by lschmierer** [comment]
I ve sent you an invite!
